// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faepwrozitpyqqavyfoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZXB3cm96aXRweXFxYXZ5Zm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjQzNzQsImV4cCI6MjA2MTEwMDM3NH0.ZvzImQYZUIjao2ILZjpR8Rb_XvRccEJOT-PRhoApvag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);